// studies/webnode/app-react-redux/app-tiny-modules/public/issues/issue-box.jsx
'use strict'

/* globals Component, connect, Row, Col, Button, Form, moment */
/* globals LinkView, DeleteIssue, CommentBox */
/* globals store, getIssues, openComment, closeComment, submitComment */

/* ******************** IssueBox ******************** */

class IssueBoxComp extends Component {
  componentWillMount () {
    const { dispatch } = this.props
    const issuekey = this.props.issuekey || this.props.match.params.key
    const issueIndex = store.getState().data.issues.findIndex(issue => issue.key === issuekey)
    if (issueIndex < 0) { dispatch(getIssues(dispatch)) }
  }

  render () {
    const container = this.props.issuekey ? 'container-fluid' : 'container'
    const fontSize = this.props.issuekey ? {'font-size': '11px'} : undefined
    const iconSize = this.props.issuekey ? '11px' : '16px'
    const issuekey = this.props.issuekey || this.props.match.params.key
    const issueIndex = store.getState().data.issues.findIndex(issue => issue.key === issuekey)
    const issue = store.getState().data.issues[issueIndex]
    const comments = issue && issue.fields.comment.comments
    const { isFetching, issues } = this.props.data
    const { isOpen } = this.props.comment
    return (
      <div>
        {isFetching && issues.length === 0 && <p><b>Loading...</b></p>}
        {!isFetching && issues.length === 0 && <p><b>Empty.</b></p>}
        {issues.length > 0 && issue !== undefined &&
        <div>

          <div className={container}>
            <Col lg={6}>
              Issue <LinkView view={`/issue/${issuekey}`}>{issuekey}</LinkView>
            </Col>
            <Col lg={6} className='text-right'>
              <DeleteIssue issuekey={issuekey}>Delete</DeleteIssue>
            </Col>
          </div>

          <div className={container}><hr /></div>

          <div className={container}>
            <b>Summary:</b>
            &nbsp;&nbsp;&nbsp;&nbsp;
            {issue.fields.summary}
          </div>

          <div className={container} style={fontSize}>

            <Col lg={8} md={12} sm={12} xs={12}>
              <div className={'container-fluid'}>
                <Col lg={6} md={6} sm={6} xs={12}>
                  <Col lg={6} md={6} sm={5} xs={5} className='text-right'>
                    <p>{''}</p>
                    <b>Type:</b><br />
                    <b>Priority:</b><br />
                    <b>Affects&nbsp;Version/s:</b><br />
                    <b>Component/s:</b><br />
                    <b>Labels:</b>
                  </Col>
                  <Col lg={6} md={6} sm={7} xs={7}>
                    <p>{''}</p>
                    <img src={issue.fields.issuetype.iconUrl} height={iconSize} width={iconSize} />&nbsp;
                    {issue.fields.issuetype.name}<br />
                    <img src={issue.fields.priority.iconUrl} height={iconSize} width={iconSize} />&nbsp;
                    {issue.fields.priority.name}<br />
                    {(issue.fields.versions || []).map(item => item.name).join(', ')}<br />
                    {(issue.fields.components || []).map(item => item.name).join(', ')}<br />
                    {(issue.fields.labels || []).map(item => item).join(', ')}
                  </Col>
                </Col>
                <Col lg={6} md={6} sm={6} xs={12}>
                  <Col lg={6} md={6} sm={5} xs={5} className='text-right'>
                    <p>{''}</p>
                    <b>Status:</b><br />
                    <b>Resolution:</b><br />
                    <b>Fix&nbsp;Version/s:</b>
                  </Col>
                  <Col lg={6} md={6} sm={7} xs={7}>
                    <p>{''}</p>
                    <img src={issue.fields.status.iconUrl} height={iconSize} width={iconSize} />&nbsp;
                    {issue.fields.status.name}<br />
                    {issue.fields.resolution.name}<br />
                    {(issue.fields.fixVersions || []).map(item => item).join(', ')}
                  </Col>
                </Col>
              </div>
            </Col>

            <Col lg={4} md={12} sm={12} xs={12}>
              <div className={'container-fluid'}>
                <Col lg={12}>
                  <p>{''}</p>
                  <Row>
                    <Col lg={5} md={9} sm={9} xs={5} className='text-right'>
                      <b>Assignee:</b><br />
                      <b>Reporter:</b>
                    </Col>
                    <Col lg={7} md={3} sm={3} xs={7}>
                      {issue.fields.assignee.name}<br />
                      {issue.fields.reporter.name}
                    </Col>
                  </Row>
                  <p>{''}</p>
                  <Row>
                    <Col lg={5} md={9} sm={9} xs={5} className='text-right'>
                      <b>Created:</b><br />
                      <b>Updated:</b>
                    </Col>
                    <Col lg={7} md={3} sm={3} xs={7}>
                      <span title={moment(issue.fields.created).format('YYYY/MM/DD HH:mm:ss')}>
                        {moment(issue.fields.created).fromNow()}
                      </span><br />
                      <span title={moment(issue.fields.updated).format('YYYY/MM/DD HH:mm:ss')}>
                        {moment(issue.fields.updated).fromNow()}
                      </span><br />
                    </Col>
                  </Row>
                </Col>
              </div>
            </Col>

          </div>

          <div className={container}>
            <p>{''}</p>
            <p><b>Description:</b></p>
            <pre>{issue.fields.description}</pre><p>{''}</p>
          </div>

          <div className={container}><hr /></div>

          <div className={container}>
            {isFetching && comments.length === 0 && <p><b>Loading...</b></p>}
            {!isFetching && comments.length === 0 && <p><b>No comment yet</b></p>}
            {comments.length > 0 &&
              <div><b>Comments:</b><p>{''}</p>
                {comments.map(comment => <CommentBox issuekey={issue.key}>{comment}</CommentBox>)}
              </div>}
            <p>{''}</p>
            <Form onSubmit={this._handleSubmit.bind(this)} onBlur={this._handleBlur.bind(this)}>
              <textarea
                className='form-control' rows={1} placeholder='Add comment:' ref='comment'
                onFocus={this._handleFocus.bind(this)} />
              {isOpen && <Button bsStyle='primary' type='submit'>Submit</Button>}
            </Form>
          </div>

        </div>}
      </div>
    )
  }

  _closeComment () {
    this.refs.comment.value = ''
    this.refs.comment.rows = this.rows
    this.props.onBlur()
  }

  _handleFocus (event) {
    this.rows = event.target.rows
    event.target.rows = 3
    this.props.onFocus()
  }

  _handleBlur (event) {
    if (!event.relatedTarget || event.relatedTarget.type !== 'submit') {
      this._closeComment()
    }
  }

  _handleSubmit (event) {
    event.preventDefault()
    const issuekey = this.props.issuekey || this.props.match.params.key
    this.props.onSubmit(issuekey, this.refs.comment.value)
    this._closeComment()
  }
}

const mapIssueBox = {
  mapStateToProps: (state, ownProps) => { return { data: state.data, comment: state.comment } },
  mapDispatchToProps: (dispatch, ownProps) => {
    return {
      dispatch,
      onFocus: () => dispatch(openComment()),
      onBlur: () => dispatch(closeComment()),
      onSubmit: (issuekey, comment) => submitComment(dispatch, issuekey, comment)
    }
  }
}

const IssueBox = connect( // eslint-disable-line no-unused-vars
  mapIssueBox.mapStateToProps,
  mapIssueBox.mapDispatchToProps
)(IssueBoxComp)

// studies/webnode/app-tsc-angular/app-style-material/src/app/issue-box/issue-box.component.ts
import { Component, OnInit, Input } from '@angular/core';
import { ActivatedRoute } from '@angular/router';
import { NgRedux, select } from '@angular-redux/store';

import { Issue } from '../classes/issue';
import { IAppState } from '../store/model';
import { StoreModule } from '../store/store.module';
import { IssueService }  from '../services/issue.service';
import { DataActions, ViewActions } from '../store/actions';

@Component({
  selector: 'app-issue-box',
  templateUrl: './issue-box.component.html',
  styleUrls: ['./issue-box.component.css']
})
export class IssueBoxComponent implements OnInit {

  @Input() issue: Issue;
  @select(['data', 'isFetching']) isFetching: boolean;

  private store: NgRedux<IAppState>;
  private iconSize = "16px;"
  private isCommentOpen = false;
  private commentRows = 1;

  constructor(
    private route: ActivatedRoute,
    private ngRedux: NgRedux<IAppState>,
    private storeModule: StoreModule,
    private issueService: IssueService,
    private dataActions: DataActions,
    private viewActions: ViewActions,
  ) {
    this.store = storeModule.store;
  }

  ngOnInit(): void {
    if (!this.issue) {
      // We navigate to this page
      const key = this.route.snapshot.paramMap.get('key');
      this.issue = this.issueService.getIssue(key);

      // We open the app at any page
      if (!this.issue) {
        // Subscribe to getIssue(key) and setActiveIssue(this.issue.key) for navigation consistency
        this.ngRedux.select(['data', 'issues']).subscribe((issues: Issue[]) => {
          this.issue = this.issueService.getIssue(key);
          if (this.issue && this.issue.key !== this.store.getState().data.activeIssue) {
            this.dataActions.setActiveIssue(this.issue.key);
          }
        })
        // No need to getIssues() twice here and from parent
        if (!this.store.getState().data.isFetching) {
          this.issueService.getIssues();
        }
      }
    }
  }

  deleteIssue(): void {
    this.viewActions.setView('/issues');
    this.issueService.deleteIssue(this.issue.key);
  }

  deleteComment(comment: {id: string}): void {
    this.issueService.deleteComment(this.issue.key, comment.id);
  }

  closeComment(): void {
    // this.refs.comment.value = ''
    // this.refs.comment.rows = this.commentRows
    this.isCommentOpen = false;
  }

  submitComment(event: any): void {
    event.preventDefault();
    this.closeComment();
    // this.issueService.postComment(this.issue.key, {body: comment});
  }

  blurComment(event: any): void {
    if (!event.relatedTarget || event.relatedTarget.type !== 'submit') {
      this.closeComment()
    }
  }

  focusComment(event: any): void {
    this.commentRows = event.target.rows
    event.target.rows = 3
    this.isCommentOpen = true;
  }
}

<div *ngIf="isFetching && !issue">
  Loading...
</div>

<div *ngIf="!isFetching && !issue">
  Empty.
</div>

<div *ngIf="issue">

  <!-- issue.key -->
  <mat-grid-list cols="2" rowHeight="30px">
    <mat-grid-tile><div class="mat-left">
      <link-view view="/issue/{{issue.key}}" name="{{issue.key}}"></link-view>
    </div></mat-grid-tile>
    <mat-grid-tile><div class="mat-right">
      <a mat-button color="primary" routerLink="/issues" (click)="deleteIssue()">Delete</a>
    </div></mat-grid-tile>
  </mat-grid-list>

  <hr />

  <!-- issue.fields.summary -->
  <mat-grid-list cols="1" rowHeight="30px">
    <mat-grid-tile><div class="mat-left">
      <b>Summary:</b>&nbsp;&nbsp;&nbsp;&nbsp;{{issue.fields.summary}}
    </div></mat-grid-tile>
  </mat-grid-list>

  <mat-grid-list cols="24" rowHeight="30px">

  <!-- ROW 1 -->

    <!-- issue.fields.issuetype -->
    <mat-grid-tile colspan="4"><div class="mat-right">
      <b>Type:</b>
    </div></mat-grid-tile>
    <mat-grid-tile colspan="1">
      <img src="{{issue.fields.issuetype.iconUrl}}" height="16px;" width="16px;" /> <!-- {{iconSize}} -->
    </mat-grid-tile>
    <mat-grid-tile colspan="3"><div class="mat-left">
      {{issue.fields.issuetype.name}}
    </div></mat-grid-tile>

    <!-- issue.fields.status -->
    <mat-grid-tile colspan="4"><div class="mat-right">
      <b>Status:</b>
    </div></mat-grid-tile>
    <mat-grid-tile colspan="1">
      <img src="{{issue.fields.status.iconUrl}}" height="16px;" width="16px;" /> <!-- {{iconSize}} -->
    </mat-grid-tile>
    <mat-grid-tile colspan="3"><div class="mat-left">
      {{issue.fields.status.name}}
    </div></mat-grid-tile>

    <!-- issue.fields.assignee -->
    <mat-grid-tile colspan="4"><div class="mat-right">
      <b>Assignee:</b>
    </div></mat-grid-tile>
    <mat-grid-tile colspan="4"><div class="mat-left">
      {{issue.fields.assignee.name}}
    </div></mat-grid-tile>

  <!-- ROW 2 -->

    <!-- issue.fields.priority -->
    <mat-grid-tile colspan="4"><div class="mat-right">
      <b>Priority:</b>
    </div></mat-grid-tile>
    <mat-grid-tile colspan="1">
      <img src="{{issue.fields.priority.iconUrl}}" height="16px;" width="16px;" /> <!-- {{iconSize}} -->
    </mat-grid-tile>
    <mat-grid-tile colspan="3"><div class="mat-left">
      {{issue.fields.priority.name}}
    </div></mat-grid-tile>

    <!-- issue.fields.resolution -->
    <mat-grid-tile colspan="4"><div class="mat-right">
      <b>Resolution:</b>
    </div></mat-grid-tile>
    <mat-grid-tile colspan="4"><div class="mat-left">
      {{issue.fields.resolution.name}}
    </div></mat-grid-tile>

    <!-- issue.fields.reporter -->
    <mat-grid-tile colspan="4"><div class="mat-right">
      <b>Reporter:</b>
    </div></mat-grid-tile>
    <mat-grid-tile colspan="4"><div class="mat-left">
      {{issue.fields.reporter.name}}
    </div></mat-grid-tile>

  <!-- ROW 3 -->

    <!-- issue.fields.versions -->
    <mat-grid-tile colspan="4"><div class="mat-right">
      <b>Affects&nbsp;Version/s:</b>
    </div></mat-grid-tile>
    <mat-grid-tile colspan="4"><div class="mat-left">
      <span ng-repeat="item in issue.fields.versions">
        <span *ngIf="$index !== 0">{{', '}}</span>
        <span *ngIf="$index">{{$index}}-{{item}}-{{item.name}}</span>
      </span>
    </div></mat-grid-tile>

    <!-- issue.fields.fixVersions -->
<!--
    <mat-grid-tile colspan="4"><div class="mat-right">
      <b>Fix&nbsp;Version/s:</b>
    </div></mat-grid-tile>
    <mat-grid-tile colspan="4"><div class="mat-left">
      <span ng-repeat="item in (issue.fields.fixVersions || [])">
        <span *ngIf="$index">{{', '}}</span>{{item.name}}
      </span>
    </div></mat-grid-tile>
-->
    <!-- empty -->
<!--
    <mat-grid-tile colspan="8">
    </mat-grid-tile>
-->

  <!-- ROW 4 -->

    <!-- issue.fields.components -->
<!--
    <mat-grid-tile colspan="4"><div class="mat-right">
      <b>Component/s:</b>
    </div></mat-grid-tile>
    <mat-grid-tile colspan="4"><div class="mat-left">
      <span ng-repeat="item in (issue.fields.components || [])">
        <span *ngIf="$index">{{', '}}</span>{{item.name}}
      </span>
    </div></mat-grid-tile>
-->

    <!-- empty -->
    <mat-grid-tile colspan="8">
    </mat-grid-tile>

    <!-- empty -->
    <mat-grid-tile colspan="8">
    </mat-grid-tile>

    <!-- issue.fields.created -->
<!--
    <mat-grid-tile colspan="4"><div class="mat-right">
      <b>Created:</b>
    </div></mat-grid-tile>
    <mat-grid-tile colspan="4"><div class="mat-left">
      <span title={{moment(issue.fields.created).format('YYYY/MM/DD HH:mm:ss')}}>
        {{moment(issue.fields.created).fromNow()}}
      </span>
    </div></mat-grid-tile>
-->

  <!-- ROW 5 -->

    <!-- issue.fields.labels -->
<!--
    <mat-grid-tile colspan="4"><div class="mat-right">
      <b>Labels:</b>
    </div></mat-grid-tile>
    <mat-grid-tile colspan="4"><div class="mat-left">
      <span ng-repeat="item in (issue.fields.labels || [])">
        <span *ngIf="$index">{{', '}}</span>{{item.name}}
      </span>
    </div></mat-grid-tile>
-->

    <!-- empty -->
    <mat-grid-tile colspan="8">
    </mat-grid-tile>

    <!-- empty -->
    <mat-grid-tile colspan="8">
    </mat-grid-tile>

    <!-- issue.fields.updated -->
<!--
    <mat-grid-tile colspan="4"><div class="mat-right">
      <b>Updated:</b>
    </div></mat-grid-tile>
    <mat-grid-tile colspan="4"><div class="mat-left">
      <span title={{moment(issue.fields.updated).format('YYYY/MM/DD HH:mm:ss')}}>
        {{moment(issue.fields.updated).fromNow()}}
      </span>
    </div></mat-grid-tile>
-->

  </mat-grid-list>

  <!-- issue.fields.description -->
  <mat-grid-list cols="1">
    <mat-grid-tile><div class="mat-left">
      <p><b>Description:</b></p>
      <pre>{{issue.fields.description}}</pre>
    </div></mat-grid-tile>
  </mat-grid-list>

  <hr />

  <!-- issue.fields.comment.comments -->

  <div *ngIf="isFetching && issue.fields.comment.comments.length === 0">
    Loading...
  </div>

  <div *ngIf="!isFetching && issue.fields.comment.comments.length === 0">
    Empty.
  </div>

  <div *ngIf="issue.fields.comment.comments.length">
    <mat-grid-list cols="1">
      <mat-grid-tile><div class="mat-left">
        <b>Comments:</b>
      </div></mat-grid-tile>
<!--
      <ul>
        <li *ngFor="let comment of (issue.fields.comment.comments || [])">
          <mat-grid-tile><div class="mat-left">
            <i>
              Posted by {{comment.author.name}}{{' '}}
              <span title={{moment(comment.created).format('YYYY/MM/DD HH:mm:ss')}}>
                {{moment(comment.created).fromNow()}}
              </span>{{' '}}
              (<button mat-button class="mat-small" color="primary" (click)="deleteComment(comment)">Delete</button>)
            </i>
            <br />
            <pre>{{comment.body}}</pre>
          </div></mat-grid-tile>
        </li>
      </ul>
-->
<!--
      {{(issue.fields.comment.comments || []).map(comment => (
        <mat-grid-tile><div class="mat-left">
          <i>
            Posted by {{comment.author.name}}{{' '}}
            <span title={{moment(comment.created).format('YYYY/MM/DD HH:mm:ss')}}>
              {{moment(comment.created).fromNow()}}
            </span>{{' '}}
            (<button mat-button class="mat-small" color="primary" (click)="deleteComment(comment)">Delete</button>)
          </i>
          <br />
          <pre>{{comment.body}}</pre>
        </div></mat-grid-tile>
      ))}}
-->
    </mat-grid-list>

<!--
    <form (submit)="submitComment()" (blur)="blurComment()">
      <textarea rows="1" placeholder="Add comment:" (focus)="focusComment() />
      <div *ngIf="isCommentOpen">
        <button mat-button color="primary">Submit</button>
      </div>
    </form>
-->

  </div>

</div>
